### ISSUE TITLE
sometimes get error from "bundle.js“ like the picture，I think it's a bug.

### ISSUE THREAD

**Issue by flyfatty** [optuna/optuna-dashboard#66] opened 2021-04-05 02:09 UTC
![image](https://user-images.githubusercontent.com/18288589/113529759-e320c080-95f6-11eb-96da-b332fcd09517.png)
![image](https://user-images.githubusercontent.com/18288589/113529774-f5026380-95f6-11eb-80e5-361a6baa28e9.png)

**Comment by c-bata** [comment] 2021-04-05 07:10
Hi @flyfatty, thank you for reporting!

Could you tell me the version of optuna-dashboard and your objective function?

**Comment by flyfatty** [comment] 2021-04-05 13:54
```
optuna-dashboard==0.3.1
optuna==2.5.0
allennlp==1.5.0
```
I am using allennlp==1.5.0 which is lower than 2.0 , so I can only use optuna==2.5.0.

> Hi @flyfatty, thank you for reporting!
> 
> Could you tell me the version of optuna-dashboard and your objective function?

**Comment by c-bata** [comment] 2021-04-05 14:00
Thank you! Is it possible to share your objective function or a script to reproduce this problem?

**Comment by c-bata** [comment] 2021-04-10 10:00
Let me close this issue since it is difficult to fix this problem from the information you reported here.
This problem may possibly be fixed from the next release because I added changes where `Array.forEach()` is used.

Thank you for reporting.

**Closed by c-bata** 2021-04-10 10:00 UTC
Labels: bug
