### ISSUE TITLE
Failed to fetch study (id=1)

### ISSUE THREAD

**Issue by Zepp3** [optuna/optuna-dashboard#113] opened 2021-06-21 12:07 UTC
Hi!

I always get the error above and don't know how to solve it.
In the .db file stands: "Error! /Josef/CTGAN/CTGAN_tryout.db ist not UTF-8 encoded. Saving disabled. See Console for more details."
But the default value for encoding of the storage command should be UTF-8, isn't it?
I use a jupyter notebook for running the code.
Thanks in advance!

**Comment by c-bata** [comment] 2021-06-21 12:25
Let me close this issue since there are no steps and contexts to reproduce the problem.
https://github.com/optuna/optuna-dashboard/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Closed by c-bata** 2021-06-21 12:25 UTC
Labels: bug

**Comment by Zepp3** [comment] 2021-06-21 12:31
I can not give more context except that I initialized an optuna dashboard for my GAN running in a jupyter notebook and therefore writing the .db file in jupyter notebook. My guess is that the notebook can't handle the .db file and therefore does not encode it like UTF-8 and the solution my be to let the .bd file end on .txt. But I wanted to ask if someone already made similar experiences.
