### ISSUE TITLE
Dashboard of a study throws JS error

### ISSUE THREAD

**Issue by pyscorcher** [optuna/optuna-dashboard#101] opened 2021-06-03 07:32 UTC
# Bug reports
I have an experiment running with a simple study, to which I manually suggested some parameters (via. `enqueue_trial`). After that trial was finished, I could still open `http://127.0.0.1:8080` to show the list of all studies in my `sqlite` file, but as soon as I clicked that study, the browser briefly shows the familiar interface but immediately switches to a blank (white site). The console shows following error message:

```
TypeError: n.union_search_space is undefined
    Xc http://127.0.0.1:8080/static/bundle.js:2
    Yi http://127.0.0.1:8080/static/bundle.js:2
    xs http://127.0.0.1:8080/static/bundle.js:2
    fl http://127.0.0.1:8080/static/bundle.js:2
    cl http://127.0.0.1:8080/static/bundle.js:2
    rl http://127.0.0.1:8080/static/bundle.js:2
    Wa http://127.0.0.1:8080/static/bundle.js:2
    unstable_runWithPriority http://127.0.0.1:8080/static/bundle.js:2
    Ha http://127.0.0.1:8080/static/bundle.js:2
    Wa http://127.0.0.1:8080/static/bundle.js:2
    Ga http://127.0.0.1:8080/static/bundle.js:2
    yl http://127.0.0.1:8080/static/bundle.js:2
    unstable_runWithPriority http://127.0.0.1:8080/static/bundle.js:2
    Ha http://127.0.0.1:8080/static/bundle.js:2
    vl http://127.0.0.1:8080/static/bundle.js:2
    gl http://127.0.0.1:8080/static/bundle.js:2
    F http://127.0.0.1:8080/static/bundle.js:2
    onmessage http://127.0.0.1:8080/static/bundle.js:2
    53 http://127.0.0.1:8080/static/bundle.js:2
    r http://127.0.0.1:8080/static/bundle.js:2
    3840 http://127.0.0.1:8080/static/bundle.js:2
    r http://127.0.0.1:8080/static/bundle.js:2
    4448 http://127.0.0.1:8080/static/bundle.js:2
    r http://127.0.0.1:8080/static/bundle.js:2
    3935 http://127.0.0.1:8080/static/bundle.js:2
    r http://127.0.0.1:8080/static/bundle.js:2
    <anonymous> http://127.0.0.1:8080/static/bundle.js:2
    <anonymous> http://127.0.0.1:8080/static/bundle.js:2
    <anonymous> http://127.0.0.1:8080/static/bundle.js:2
bundle.js:2:3611743
```

## Expected Behavior
I expect the dashboard to show up as usual.

## Current Behavior and Steps to Reproduce
Make a new study, add some trials. Then maybe add some new trials via `enqueue_trial` that might be outside of the previously used parameter range. Then open `optuna-dashboard`.

## Context

* `python -c 'import optuna; print(optuna.__version__)'`: 3.8.8
* `optuna-dashboard --version`: 0.3.1

**Comment by c-bata** [comment] 2021-06-03 08:48
I've just checked the study after enqueued some WAITING trials, but couldn't reproduce this problem. 
Could you share the code to reproduce this bug?

**Comment by c-bata** [comment] 2021-07-21 06:15
Let me close this issue since there is no reproducible code.

**Closed by c-bata** 2021-07-21 06:15 UTC
Labels: bug
