### ISSUE TITLE
Unable to access optuna-dashboard behind nginx proxy

### ISSUE THREAD

**Issue by wen-zheng** [optuna/optuna-dashboard#389] opened 2023-02-09 07:44 UTC
### Description

It seems that optuna-dashboard is inaccessible behind nginx proxy, the below is my proxy configurations:

```
    server {
       listen       80;
       server_name myservername;
       access_log  off;

       location / {
           proxy_pass         http://127.0.0.1:8080;
           proxy_set_header   Host             $host;
           proxy_set_header   X-Real-IP        $remote_addr;
           proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
           proxy_set_header   X-Forwarded-Proto  $scheme;
       }
     }
}
```
when I try to access myservername, I get the following errors:
![image](https://user-images.githubusercontent.com/33896328/217748403-aec70c2c-0c67-4147-8d27-58f49286760a.png)
![image](https://user-images.githubusercontent.com/33896328/217748509-e14117be-d194-4378-bef4-424cb09009ce.png)

### How to Reproduce

2. Run optuna-dashboard on 127.0.0.1:8080
3. proxy a server name to 127.0.0.1:8080
4. try to access that server name 

### Python version

3.8

### Optuna version

Output of `$ python -c 'import optuna; print(optuna.__version__)'`

### optuna-dashboard version or git revision

3.2.0.dev

### Web browser

chrome

**Comment by c-bata** [comment] 2023-02-09 07:59
Thank you for using optuna-dashboard!

Please let me close this issue as it is clearly not an Optuna Dashboard issue. I don't know the cause, but there seems to be a problem on your `nginx.conf`. You may find the cause by checking the access logs on the Optuna Dashboard side.

**Closed by c-bata** 2023-02-09 07:59 UTC
Labels: bug
