### ISSUE TITLE
optuna_dashboard wont recognise streamlit 

### ISSUE THREAD

**Issue by waassiim** [optuna/optuna-dashboard#981] opened 2024-10-24 18:23 UTC
### Description

i get error : AttributeError: module 'optuna_dashboard' has no attribute 'streamlit' when try to use aoptuna_dashboard.streamlit.render_trial_note

### How to Reproduce

just writing optuna_dashboard.streamlit.render_trial_note and try to use it 

### Python version

3.10

### Optuna version

4.0.0

### optuna-dashboard version or git revision

0.16.2

### Web browser

Google Chrome

**Comment by c-bata** [comment] 2024-11-06 03:55
@waassiim Thank you for using optuna dashboard! Could you try using `from optuna_dashboard.streamlit import render_trial_note` instead of `import optuna_dashboard`?

https://github.com/optuna/optuna-dashboard/blob/b6bcbcf88c414de8b38498b1749cedbbce87f912/python_tests/streamlit/test_streamlit_helper.py#L14-L26

Let me close this issue since this looks not a bug.

**Closed by c-bata** 2024-11-06 03:55 UTC
Labels: bug
