### ISSUE TITLE
error of optuna-dashboard

### ISSUE THREAD

**Issue by pistachio-xin** [optuna/optuna-dashboard#206] opened 2022-04-13 03:36 UTC
### Description

If the trial finished right, then I can get the results and many figures in the page of optuna-dashboard, but when the trials is interrupted, the page of optuna-dashboard is empty.

### How to Reproduce

![image](https://user-images.githubusercontent.com/81011698/163095050-7ebd7fc0-c254-456f-a38f-5043eeb8f7fc.png)
but when i open the study, it is empty.
![image](https://user-images.githubusercontent.com/81011698/163095132-95d360a5-4c8c-4f25-97e4-8ca7dc1d7754.png)

### Python version

3.8

### Optuna version

Output of `$ python -c 'import optuna; print(optuna.__version__)'`

### optuna-dashboard version or git revision

Output of `$ optuna-dashboard --version`

### Web browser

Google Chrome, Firefox, etc.

**Comment by c-bata** [comment] 2022-04-13 03:40
Sorry, I cannot reproduce this problem from your reports. May I have more detailed information? Otherwise I can't fix this prolem.

**Comment by pistachio-xin** [comment] 2022-04-13 03:50
thanks for your reply.
just try it by this code
import optuna
study_name = 'example-study'  # Unique identifier of the study.
study = optuna.create_study(study_name=study_name,directions=['minimize','minimize','minimize'],storage='sqlite:///example_m.db')
def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    y = trial.suggest_uniform('y', -10, 10)
    z = trial.suggest_uniform('z', -10, 10)
    return (x - 2) ** 2, (y - 2) ** 2, (z - 2) ** 2
import joblib
algo = optuna.samplers.TPESampler(n_startup_trials = 10, n_ei_candidates = 24)#默认最开始有10个观测值，每一次计算采集函数随机抽取24组参数组合
for i in range(0,10):

    study = optuna.create_study( sampler=algo,study_name=study_name,directions=['minimize','minimize','minimize'],storage='sqlite:///example_m.db', load_if_exists=True)
    study.optimize(objective, n_trials=3)
![image](https://user-images.githubusercontent.com/81011698/163096266-aa010abe-448f-4121-9c95-a5f4853341b1.png)
if you interrupted the study when the study just finished several trials, then open the optuna-dashboard, you will find it is empty actually.

**Comment by c-bata** [comment] 2022-04-13 03:54
Thanks! I'll try to reproduce the problem. Could you paste the output of `$ pip freeze | grep optuna`?

**Comment by pistachio-xin** [comment] 2022-04-13 04:06
You are using pip version 8.1.2, however version 22.0.4 is available.
optuna 2.10.0
Thanks a lot. By the way, if I finished the study, it is right and can get figures, just when interrupted the study, the optuna-dashboard is empty.

**Comment by c-bata** [comment] 2022-04-13 05:05
> optuna 2.10.0

Thanks! I mean I'd like to check the version of optuna-dashboard as well.

> By the way, if I finished the study, it is right and can get figures, just when interrupted the study, the optuna-dashboard is empty.

OK. You should get figures even if the study is interrupted. So something seems to be wrong.

**Comment by c-bata** [comment] 2022-04-21 02:47
Thank you for reporting. This will be fixed at #211.
I will release the new version for that within a week.

**Closed** 2022-04-21 03:09 UTC
Labels: bug

**Comment by florentdelgrange** [comment] 2022-09-19 22:17
Hi, I have the exact same problem with the new version of optuna-dashboard, and I can reproduce the issue described in this post.
Is still some quick way to fix this? Even by modifying the database?

Optuna version: 3.0.0a2
optuna-dashboard Version: 0.7.3

**Comment by c-bata** [comment] 2022-09-27 10:50
@florentdelgrange Thank you for using optuna-dashboard! This issue is resolved at v0.7.3. So the problem you bumped seems to be different with this issue. Could you file a new issue to reproduce the bug?
